export const CLEAR_LOGIN_FORM = 'CLEAR_LOGIN_FORM';
export const SET_LOGGING_IN = 'SET_LOGGING_IN';
export const SET_SIGNING_UP = 'SET_SIGNING_UP';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const SET_LOGIN_FORM_ERROR = 'SET_LOGIN_FORM_ERROR';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_LOGIN_INPUT = 'SET_LOGIN_INPUT';
export const SET_SIGNUP_INPUT = 'SET_SIGNUP_INPUT';
